name: Dependencies -  Bump versions

on:
  schedule:
    # Each day at 3:00 AM
    - cron: 0 3 * * *
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  deps-bump:
    name: Dependencies bump
    permissions:
      contents: write
      issues: write
      pull-requests: write
      # workflows: write
      security-events: read
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/renovatebot/renovate:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Dependencies bump
        id: deps-bump
        env:
          RENOVATE_TOKEN: ${{ secrets.github_token }}
          RENOVATE_ENDPOINT: https://api.github.com
          RENOVATE_PLATFORM: github
          RENOVATE_REPOSITORIES: "['kemadev/ci-cd']"
          RENOVATE_PR_HOURLY_LIMIT: 50
        run: /usr/local/sbin/renovate-entrypoint.sh
